# name of your application
MODULE = incremental_ks

# If no BOARD is found in the environment, use this default:
BOARD ?= microbit-v2

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../../..

DIRS += $(CURDIR)/../utility

include $(RIOTBASE)/Makefile.base