# name of your application
MODULE = random_ks_wasm

TESTCASE = random_ks_wasm

# If no BOARD is found in the environment, use this default:
BOARD ?= microbit-v2

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../../..

include $(RIOTBASE)/Makefile.base