include ../Makefile.tests_common

BLOBS += application/fletcher32_fc.bin

USEMODULE += embunit
USEPKG += femto-container

USEMODULE += xtimer
USEMODULE += saul
USEMODULE += saul_reg
USEMODULE += saul_default

CFLAGS += -I$(CURDIR)

include $(RIOTBASE)/Makefile.include
