# name of your application
MODULE = nrf52_temp_read_only

# If no BOARD is found in the environment, use this default:
BOARD ?= microbit-v2

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../../..

include $(RIOTBASE)/Makefile.base